version: 0.0
os: linux
files:
  - source: /
    destination: /usr/cddemo
permissions:
  - object: /usr/cddemo/scripts
    pattern: "*.sh"
    owner: ubuntu
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  # ValidateService:
  #   - location: scripts/validate_server.sh
  #     timeout: 300
  #     runas: root