---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout #check out the source code from the repository
      - run:
          name: update-npm-modules
          command: echo "Hello Word !!"

  build:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout #check out the source code from the repository
      - run:
          name: update-npm-modules
          command: echo "Hello Word !!"

workflows:
  version: 2
  pr-check-workfow:
    jobs:
    - pr_check
  build-depoy-workfow:
    jobs:
    - build
  