---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout #check out the source code from the repository
      - run:
          name: update-npm-modules
          command: |
            npm install

  build_deploy:
    docker:
      - image: circleci/node:10.12.0
        environment:
          MYSQL_ROOT_PASSWORD: "helloworld"
          MYSQL_HOST: "127.0.0.1"
          MYSQL_DATABASE: "CloudDB"
          MYSQL_PORT: 3306
          MYSQL_USERNAME: "root"
          MYSQL_DIALECT: "mysql"
          NODE_ENV: test

    steps:
      - checkout #check out the source code from the repository
      - run:
          npm install
          
      - run:
          name: start test
          command: |
            sleep 30
            npm test

workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check
  build_deploy:
    jobs:
    - build_deploy:
        filters:
            branches:
              only:
                - master
  