---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout #check out the source code from the repository
      - run:
          name: update-npm-modules
          command: echo "Hello Word !!"

  build:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout #check out the source code from the repository
      - run:
          name: update-npm-modules
          command: echo "Hello Word !!"

  initializeDB:
    docker:
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    steps:
      - checkout #check out the source code from the repository
      - run:
          name: Waiting for MySQL to be ready
          command: >
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              sleep 10
            done
            echo Failed && exit 1
      - run:
          name: Install MySQL CLI
          command: >
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.User"


workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build-depoy-workflow:
    jobs:
    - build
  db-workflow:
    jobs:
    - initializeDB
  