---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.12.0

    steps:
      - checkout: #check out the source code from the repository
          path: /home/circleci/project/webapp/

      - run:
          name: npm installation and check directory
          command: |
            cd /home/circleci/project/webapp/
            npm install
            pwd
          
      - run:
          name: start test
          command: |
            cd /home/circleci/project/webapp/
            sleep 10
            npm test

      - run:
          name: remove node_modules
          command: |
            cd /home/circleci/project/webapp/
            rm -rf node_modules/

      - run:
          name: Install aws cli and configure
          command: |
            sudo apt-get update && sudo apt-get install python-pip
            sudo pip install awscli
            sudo aws --version
            aws configure set aws_access_key_id ${aws_access_key}
            aws configure set aws_secret_access_key ${aws_secret_key}
            aws configure set region us-east-1
            aws configure list
            pwd
            ls -al
            zip -r webapp.zip webapp/
            aws s3 cp webapp.zip s3://codedeploy.divyataneja.me --region us-east-1 
            aws deploy create-deployment \ --application-name CodeDeployAppName \ 
            --s3-location bucket=codedeploy.divyataneja.me,key=webapp.zip

            
  build_deploy:
    docker:
      - image: circleci/node:10.12.0
        environment:
          MYSQL_ROOT_PASSWORD: "helloworld"
          MYSQL_HOST: "127.0.0.1"
          MYSQL_DATABASE: "CloudDB"
          MYSQL_PORT: 3306
          MYSQL_USERNAME: "root"
          MYSQL_DIALECT: "mysql"
          NODE_ENV: test

    steps:
      - checkout #check out the source code from the repository
      - run:
          npm install
          
      - run:
          name: start test
          command: |
            sleep 10
            npm test

workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check
  build_deploy:
    jobs:
    - build_deploy:
        filters:
            branches:
              only:
                - master
  